using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace InvoiceSystem.Models
{
    public class Invoice
    {
        /// <summary>
        /// The DB Primary Key.
        /// </summary>
        public int? InvoiceID { get; set; }

        /// <summary>
        /// An auto-generated number for the invoice.
        /// </summary>
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// The date the of the invoice.
        /// </summary>
        public DateTime InvoiceDate { get; set; }

        /// <summary>
        /// The total cost of the invoice.
        /// </summary>
        public decimal TotalPrice { get; set; }

        /// <summary>
        /// A list of all InvoiceItems attached to the invoice.
        /// </summary>
        public IEnumerable<InvoiceItem> ListItems { get; set; }

        /// <summary>
        /// Static access to the Database
        /// </summary>
        public static Database DB = new Database();

        
        #region Constructors

        /// <summary>
        /// The default constructor.
        /// </summary>
        public Invoice()
        {

        }

        /// <summary>
        /// The constructor that uses all properties to create an object.
        /// </summary>
        /// <param name="invoiceID">The DB Primary Key.</param>
        /// <param name="invoiceNumber">The auto-generated number for the invoice.</param>
        /// <param name="invoiceDate">The date of the invoice.</param>
        /// <param name="totalPrice">The total cost of the invoice.</param>
        public Invoice(int invoiceID, string invoiceNumber, DateTime invoiceDate, decimal totalPrice)
        {
            try
            {
                this.InvoiceID = invoiceID;
                this.InvoiceNumber = invoiceNumber;
                this.InvoiceDate = invoiceDate;
                this.TotalPrice = totalPrice;
            }
            catch (Exception ex)
            {
                throw new Exception(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." +
                    MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message);
            }
        }

        #endregion


        #region DB Queries

        /// <summary>
        /// Queries the DB for ALL invoices, creates a list of Invoice objects, and returns it.
        /// </summary>
        /// <returns>A list of all Invoice objects from the DB.</returns>
        public static List<Invoice> GetInvoices()
        {
            try
            {
                // Set up the variables
                string SQL = "SELECT * FROM Invoice";
                int numRows = 0;
                List<Invoice> invoiceList = new List<Invoice>();

                // Call the DB query
                DataSet invoiceDS = DB.ExecuteSQLStatement(SQL, ref numRows);

                // Add each item to the list
                foreach (DataRow dr in invoiceDS.Tables[0].Rows)
                {
                    invoiceList.Add(new Invoice(Convert.ToInt32(dr["InvoiceID"].ToString()), 
                        dr["InvoiceNumber"].ToString(),
                        DateTime.Parse(dr["InvoiceDate"].ToString()), 
                        Convert.ToDecimal(dr["TotalPrice"].ToString()) ) );
                }

                return invoiceList;
            }
            catch (Exception ex)
            {
                throw new Exception(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." +
                    MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message);
            }
        }

        /// <summary>
        /// Saves the current Invoice object in the DB (INSERTs or UPDATEs)
        /// </summary>
        public void Save()
        {
            try
            {
                if (this.InvoiceID != null)
                {
                    Update();
                    return;
                }

                if (this.InvoiceDate == null)
                {
                    throw new Exception("Could not save Invoice record: Insufficient information provided.");
                }
                
                foreach (var line in this.ListItems)
                {
                    this.TotalPrice += line.Quantity * line.LineItem.ItemPrice;
                }

                // Builds a SQL string to save a record with the invoice date and the TotalPrice.
                // The InvoiceID and InvoiceNumber are auto-generated by the DB.
                string SQL = "INSERT INTO Invoice " + // INSERT INTO Invoice
                    "(InvoiceDate, TotalPrice)" + // (InvoiceDate, TotalPrice)
                    "VALUES (\"" + this.InvoiceDate.ToString() + "\", " + // VALUES ("____", 
                     this.TotalPrice.ToString() + ")"; // "____")
                int id = 0;
                DB.ExecuteNonQuery(SQL, ref id);
                this.InvoiceID = id;
            }
            catch (Exception ex)
            {
                throw new Exception(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." +
                    MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message);
            }
        }

        /// <summary>
        /// Updates the DB record for the current Invoice object.
        /// </summary>
        public void Update()
        {
            try
            {
                string SQL = "UPDATE Invoice " + // UPDATE Invoice
                    "SET InvoiceDate = \"" + this.InvoiceDate.ToString() + "\", " + // SET InvoiceDate = "_____", 
                    "TotalPrice = \"" + this.TotalPrice.ToString() + "\"" + // TotalPrice = "_____"
                    " WHERE InvoiceID = " + this.InvoiceID; // WHERE InvoiceID = __
                int numRows;

                numRows = DB.ExecuteNonQuery(SQL);
            }
            catch (Exception ex)
            {
                throw new Exception(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." +
                    MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message);
            }
        }

        /// <summary>
        /// Deletes the record for the current Invoice from the DB
        /// </summary>
        public void Delete()
        {
            try
            {
                // Delete the associated InvoiceItems
                string SQL = "DELETE FROM InvoiceItem WHERE InvoiceID = " + this.InvoiceID;
                int numRows;

                DB.ExecuteNonQuery(SQL);

                // Delete the Invoice
                SQL = "DELETE FROM Invoice WHERE InvoiceID = " + this.InvoiceID;

                numRows = DB.ExecuteNonQuery(SQL);
            }
            catch (Exception ex)
            {
                throw new Exception(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." +
                    MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message);
            }
        }

        #endregion


        /// <summary>
        /// Overrides the ToString() method.
        /// </summary>
        /// <returns>Invoice #[InvoiceNumber] ([InvoiceDate]): $[TotalPrice]</returns>
        public override string ToString()
        {
            try
            {
                return "Invoice #" + this.InvoiceNumber + " (" + this.InvoiceDate.ToShortDateString() + "): " + this.TotalPrice.ToString("C");
            }
            catch (Exception ex)
            {
                throw new Exception(MethodInfo.GetCurrentMethod().DeclaringType.Name + "." +
                    MethodInfo.GetCurrentMethod().Name + " -> " + ex.Message);
            }
        }
    }
}
